repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=120]
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev : 5.0.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E501,W503"
