CONFIG_FILE_PATH = "./config.yaml"

INPUT_FILE = "input_file_path"

DAYS_EXPIRED_LIMIT = 15
DAYS_EXPIRING_LIMIT = 60

SHEET_INPUT = "nt_users"
SHEET_EXPIRED = "expired_users"
SHEET_EXPIRES_SOON = "expiring_soon_users"
SHEET_ALL_USERS = "all_users"
SHEETS_NAME_LIST = [SHEET_EXPIRED, SHEET_EXPIRES_SOON, SHEET_ALL_USERS]

LAST_RELEVANT_ELEMENT_POSITION = 40

NAME_COLUMN = "D"
NT_USER_COLUMN = "E"
EXPIRATION_DATE_COLUMN = "F"
COLUMNS_LIST = [NAME_COLUMN, NT_USER_COLUMN, EXPIRATION_DATE_COLUMN]

COLUMN_WIDTH = 30