CONFIG_FILE_PATH = "./config.yaml"

INPUT_FILE = "input_file_path"

DAYS_EXPIRED_LIMIT = 0
DAYS_EXPIRING_15_LIMIT = 15
DAYS_EXPIRING_30_LIMIT = 30
DAYS_EXPIRING_60_LIMIT = 60

SHEET_INPUT = "nt_users"
SHEET_EXPIRED = "expired_users"
SHEET_EXPIRES_15 = "expiring_15_users"
SHEET_EXPIRES_30 = "expiring_30_users"
SHEET_EXPIRES_60 = "expiring_60_users"
SHEET_ALL_USERS = "all_users"
SHEETS_NAME_LIST = [SHEET_EXPIRED, SHEET_EXPIRES_15, SHEET_EXPIRES_30, SHEET_EXPIRES_60, SHEET_ALL_USERS]

LAST_RELEVANT_ELEMENT_POSITION = 40

FIRST_COLUMN = 4
NUMBER_OF_COLUMNS = 3
COLUMN_WIDTH = 30

NAME_COLUMN = "D"
NT_USER_COLUMN = "E"
EXPIRATION_DATE_COLUMN = "F"
COLUMNS_LIST = [NAME_COLUMN, NT_USER_COLUMN, EXPIRATION_DATE_COLUMN]

TABLE_STYLE = "TableStyleLight13"
TABLE_NAME = "nt_users_table"
TABLE_NAME_COLUMN = "Name"
TABLE_NT_USER_COLUMN = "NT_User"
TABLE_EXPIRATION_DATE_COLUMN = "Expiration Date"
